/*
 * javaGRID - A Grid-Based, Distributed Processing Framework for Embarrassingly Parallel Problems
 *  
 * Submitted as part of a Master's thesis in Advanced Software Engineering
 *
 * Author: Alan Suleiman - alan.suleiman@kcl.ac.uk
 * 
 * August 2015
 */
package javagrid.common;

import java.io.Serializable;

/**
 * Generated by {@link javagrid.utils.Heartbeat} as reflection of the node's current status e.g. resource usage information
 */
public class Pulse implements Serializable {

	private static final long serialVersionUID = 8482027808260298395L;
	private String clientType;
	private String uuid;
	private long jvmTotalMemory;
	private long jvmUsed;
	private long jvmFree;
	private double userCPU;
	private double systemCPU;
	private double idleCPU;
	private double combinedCPU;
	private double jvmCPU;

	/**
	 * @param clientType flag indicator.  Either {Master, Worker} and used by the TaskSpace to identify source of node message
	 * @param uuid used to identify the source of this node specification message
	 * @param jvmTotalMemory the currently allocated memory to the JVM
	 * @param jvmUsed self-explanatory
	 * @param jvmFree self-explanatory
	 * @param userCPU self-explanatory
	 * @param systemCPU self-explanatory
	 * @param idleCPU self-explanatory
	 * @param combinedCPU userCPU + systemCPU
	 * @param jvmCPU self-explanatory
	 */
	public Pulse(String clientType, String uuid, long jvmTotalMemory, long jvmUsed, long jvmFree, double userCPU, double systemCPU,
			double idleCPU, double combinedCPU, double jvmCPU) {

		this.clientType = clientType;
		this.uuid = uuid;
		this.jvmTotalMemory = jvmTotalMemory;
		this.jvmUsed = jvmUsed;
		this.jvmFree = jvmFree;
		this.userCPU = userCPU;
		this.systemCPU = systemCPU;
		this.idleCPU = idleCPU;
		this.combinedCPU = combinedCPU;
		this.jvmCPU = jvmCPU;
	}



	public String getClientType() {
		return clientType;
	}
	public String getUuid() {
		return uuid;
	}
	public long getJvmTotalMemory() {
		return jvmTotalMemory;
	}
	public long getJvmUsed() {
		return jvmUsed;
	}
	public long getJvmFree() {
		return jvmFree;
	}
	public double getUserCPU() {
		return userCPU;
	}
	public double getSystemCPU() {
		return systemCPU;
	}
	public double getIdleCPU() {
		return idleCPU;
	}
	public double getCombinedCPU() {
		return combinedCPU;
	}
	public double getJvmCPU() {
		return jvmCPU;
	}
	public void setClientType(String clientType) {
		this.clientType = clientType;
	}
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	public void setJvmTotalMemory(long jvmTotalMemory) {
		this.jvmTotalMemory = jvmTotalMemory;
	}
	public void setJvmUsed(long jvmUsed) {
		this.jvmUsed = jvmUsed;
	}
	public void setJvmFree(long jvmFree) {
		this.jvmFree = jvmFree;
	}
	public void setUserCPU(double userCPU) {
		this.userCPU = userCPU;
	}
	public void setSystemCPU(double systemCPU) {
		this.systemCPU = systemCPU;
	}
	public void setIdleCPU(double idleCPU) {
		this.idleCPU = idleCPU;
	}
	public void setCombinedCPU(double combinedCPU) {
		this.combinedCPU = combinedCPU;
	}
	public void setJvmCPU(double jvmCPU) {
		this.jvmCPU = jvmCPU;
	}

}
